wandb: False # use wandb to log the results
force_regenerate: True
# forced to regenerate the data even if the result file exists

# stage: reverse/reservation
stage: reservation

# the language and task for the data generation. please make sure to provide the correct dataset
language: en
language_list:
- zh
- en
task: legal
task_list:
- medical
- legal
- financial

model_list:
- llama
- glm
- qwen
- gpt-4o-mini
model:
  model_name: gpt-4o-mini
  model_path:
    llama: /public/model/hub/LLM-Research/Meta-Llama-3-1-8B-Instruct/
    glm: /root/.cache/modelscope/hub/ZhipuAI/glm-4-9b-chat-hf/
    qwen: /public/model/hub/qwen/
    gpt-4o-mini: api--https://api.gptapi.us/v1/chat/completions--gpt-4o-mini--null

batch_size: 8

# The following is the default config for the data generation
# Please dont change the config in the data generation script unless you know what you are doing
loop_count: 5
data:
  doc_count: 500

  min_length: 1
  max_length: 2000
tokenizer_kwargs:
  padding: True
  max_length: 512
  truncation: True
  add_special_tokens: True
gen_kwargs:
  max_new_tokens: 500

# chart config
color_family:
- '#2A557F'
- '#FFCD6E'
- '#F05076'
- '#45779C'
- '#606060'
- '#E465B0'

color_family2:
- '#FBECB2'
- '#F8BDEB'
- '#5272F2'
- '#7ED7C1'
- '#072541'
