wandb: True # use wandb to log the results
force_regenerate: False
# forced to regenerate the data even if the result file exists

# stage: reverse/reservation
stage: reverse

# the language and task for the data generation. please make sure to provide the correct dataset
language: zh
language_list:
- zh
- en
task: legal
task_list:
- medical
- legal
- financial

model_list:
- gpt-4o-mini
- llama
- glm
- qwen
# - deepseek-r1
model:
  model_name: llama
  model_path:
    llama: /public/model/hub/LLM-Research/Meta-Llama-3-1-8B-Instruct/
    glm: /root/.cache/modelscope/hub/ZhipuAI/glm-4-9b-chat-hf/
    qwen: /public/model/hub/qwen/qwen2-7b-instruct/
    gpt-4o-mini:
      type: api
      url: https://api.gptapi.us/v1/chat/completions
      model_name: gpt-4o-mini
    deepseek-r1:
      type: api
      url: https://dashscope.aliyuncs.com/compatible-mode/v1
      key: ""
      model_name: deepseek-r1
    gpt-3.5-turbo:
      type: api
      url: https://api.gptapi.us/v1/chat/completions
      model_name: gpt-3.5-turbo

batch_size: 8

# The following is the default config for the data generation
# Please dont change the config in the data generation script unless you know what you are doing
loop_count: 5
data:
  doc_count: 500
  min_length: 1
  max_length: 2000
tokenizer_kwargs:
  padding: True
  max_length: 512
  truncation: True
  add_special_tokens: True
gen_kwargs:
  max_new_tokens: 500
  do_sample: False
  temperature: 0.0
# mongodb
mongodb:
  url: mongodb://admin:dengmen520@172.17.0.1:27017/
  db_name: rblu
  collection_name: default
# chart config
color_family:
- '#2A557F'
- '#FFCD6E'
- '#F05076'
- '#45779C'
- '#606060'

color_family2:
- '#FBECB2'
- '#F8BDEB'
- '#5272F2'
- '#7ED7C1'
- '#072541'
