from transformers import pipeline
from proxy import set_proxy

set_proxy()
# 加载模型和tokenizer
model_name = "/public/model/hub/ZhipuAI/glm-4-9b-chat"  # 替换为实际的模型名称
text_generator = pipeline("text-generation", model=model_name, device_map="auto",trust_remote_code=True)

# 生成文本
prompts = [
    "The following text comes from a response to a conversation, which most likely asks the following question?(Please reply in this format:The question is most likely......)\n\n1. **Regular Check-ups**: Schedule regular appointments with your healthcare provider to monitor your blood glucose levels. This will help you understand your current status and make informed decisions about your health.\n\n2. **Healthy Lifestyle Changes**:\n   - **Diet**: Focus on a balanced diet rich in whole grains, fruits, vegetables, and lean proteins. Avoid sugary drinks and foods high in saturated fats and processed sugars.\n   - **Physical Activity**: Aim for at least 30 minutes of moderate-intensity exercise most days of the week.",
    "The following text comes from a response to a conversation, which most likely asks the following question?(Please reply in this format:The question is most likely......)\n\n1. **Interest Rate Sensitivity**: While this is a first-order risk, its implications can be explored further. As rates rise, mortgage REITs face challenges in refinancing their assets at lower rates, potentially leading to higher costs. Moreover, rising rates might reduce the demand for new mortgages, affecting the volume of income generated by mortgage REITs.\n\n2. **Credit Risk**: This refers not just to the direct credit risk of borrowers but also to the risk of defaults in the broader economy. A downturn in the economy could lead to higher unemployment, which in turn increases the likelihood of mortgage defaults. Additionally, the risk of defaults might extend to the underlying collateral if there's a significant drop in property values.\n\n3. **Regulatory Changes**: Changes in regulations governing mortgage REITs can significantly impact their operations. For instance, new rules around capital requirements, tax treatments, or restrictions on the types of assets they can hold can alter their profitability and growth potential.\n\n4. **Economic Downturns**: Beyond the direct effects of interest rates and credit risk, a broader economic downturn can affect consumer spending power, employment rates, and overall housing demand. This can lead to a decrease in property values and an increase in delinquencies, impacting the financial health of mortgage REITs.\n\n5. **Market Valuation**: The valuation of mortgage REITs can be influenced by factors like market sentiment, investor expectations, and the overall performance of the stock market. A sudden shift in market conditions could lead to overvaluation or undervaluation, affecting the attractiveness of these investments.\n\n6. **Technological Disruption**: Emerging technologies, such as digital lending platforms and blockchain",
]
generated_texts = text_generator(prompts, max_new_tokens=1000, num_return_sequences=1)

for prompt, text in zip(prompts, generated_texts):
    # print(f"Prompt: {prompt}")
    print(f"Generated: {text[0]['generated_text']}\n")
