mongo: 
  ip_address: 10.48.48.7
  port: 27017
  database: llm_evaluation
data:
  doc_count: 5
  min_length: 25
  max_length: 150
model: 
  model_checkpoint: /public/model/hub/qwen/qwen2-7b-instruct
eval:
  task_list:
    - law
    - finance
    - medical
  batch_size: 8
  loop: 2
  max_length_input: 1024
  gen_kwargs:
    max_new_tokens: 1024